<a href="https://colab.research.google.com/github/cjharsh/Colab-Files-with-ML/blob/master/Multiple_Linear_Regression_Student_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
data = pd.read_csv("student.csv")

In [0]:
data.head()

Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [0]:
x1 = data["Math"].values
x2 = data["Reading"].values

m = len(x1)

In [0]:
m = len(x1)
m

1000

In [0]:
x1.reshape(m,1)
x2.reshape(m,1)

array([[ 68],
       [ 81],
       [ 80],
       [ 83],
       [ 64],
       [ 84],
       [ 84],
       [ 48],
       [ 78],
       [ 78],
       [ 69],
       [ 88],
       [ 44],
       [ 78],
       [ 70],
       [ 44],
       [ 71],
       [ 48],
       [ 90],
       [ 75],
       [ 58],
       [ 66],
       [ 72],
       [ 52],
       [ 86],
       [ 90],
       [ 66],
       [ 75],
       [ 78],
       [ 82],
       [ 77],
       [ 90],
       [ 74],
       [ 69],
       [ 41],
       [ 61],
       [ 53],
       [ 77],
       [ 74],
       [ 44],
       [ 87],
       [ 77],
       [ 62],
       [ 49],
       [ 68],
       [ 72],
       [ 53],
       [ 74],
       [100],
       [ 74],
       [100],
       [ 89],
       [ 81],
       [ 51],
       [ 50],
       [ 49],
       [ 55],
       [ 50],
       [ 69],
       [ 81],
       [ 55],
       [ 92],
       [ 98],
       [ 83],
       [ 43],
       [ 92],
       [ 68],
       [ 83],
       [ 60],
       [ 58],
       [ 61],
      

In [0]:
math = data['Math'].values
write = data['Writing'].values
read =  data['Reading'].values
x = np.array([math, read])
x

array([[48, 62, 79, ..., 89, 83, 66],
       [68, 81, 80, ..., 87, 82, 66]], dtype=int64)

In [0]:
x = np.array([math, read]).T
x

array([[48, 68],
       [62, 81],
       [79, 80],
       ...,
       [89, 87],
       [83, 82],
       [66, 66]], dtype=int64)

In [0]:
y = np.array(write)

In [0]:
y

array([ 63,  72,  78,  79,  62,  85,  83,  41,  80,  77,  64,  90,  45,
        77,  70,  46,  76,  44,  85,  72,  53,  66,  75,  49,  84,  83,
        68,  66,  77,  78,  74,  83,  72,  65,  46,  66,  50,  79,  68,
        46,  86,  70,  61,  53,  72,  75,  50,  77, 100,  81, 100,  87,
        78,  48,  50,  44,  48,  43,  67,  78,  58,  91,  92,  78,  42,
        85,  73,  83,  61,  58,  60,  55,  48,  62,  68,  59,  62,  48,
        74,  63,  80,  79,  73,  79,  45,  67,  89,  77,  81,  88,  53,
        68,  79,  77,  63,  73,  60,  67, 100,  79,  26,  51,  80,  57,
        41,  78,  68,  49,  76,  41,  71,  77,  89,  86,  55,  80,  56,
        74,  85,  80,  73,  74,  86,  56,  53,  44,  41,  59,  71,  81,
        74,  78,  67,  53,  56,  75,  82,  79,  99,  76,  59,  96,  75,
        61,  56,  88,  65, 100,  79,  55,  61,  83,  74,  59,  54,  47,
        82,  74,  59,  74,  84,  59,  43,  65,  61,  78,  84,  73,  73,
        92,  63,  72,  61,  59,  70,  87,  78,  65,  73,  62,  6

In [0]:
from sklearn.linear_model import LinearRegression

In [0]:
reg = LinearRegression()

In [0]:
reg = reg.fit(x,y)

In [0]:
Y_pred = reg.predict(x)

In [0]:
r2 = reg.score(x,y)

In [0]:
r2

0.9098901726717316

In [0]:
[reg.intercept_]

[-1.462437384942021]

In [0]:
[reg.coef_]

[array([0.09600221, 0.91049989])]

In [0]:
plt.plot(x,y)